spring.application.name=ipl-crickbuzz

spring.datasource.url=jdbc:mysql://database-1.c4psuwgiupfb.us-east-1.rds.amazonaws.com:3306/ipl_crickbuzz
spring.datasource.username=admin
spring.datasource.password=IplCricbuzz2026DB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
